In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_csv('FitNotes Data/FitNotes_Export.csv')

In [22]:
data

,Date,Exercise,Category,Weight (kgs),Reps,Comment
0,2017-04-17,Deadlift,Back,150.0,3.0,NaN
1,2017-04-17,Deadlift,Back,155.0,3.0,NaN
2,2017-04-17,Deadlift,Back,160.0,3.0,NaN
3,2017-04-17,Deadlift,Back,165.0,3.0,NaN
4,2017-04-17,Deadlift,Back,170.0,3.0,NaN
5,2017-04-17,Chin Up,Back,0.0,10.0,NaN
6,2017-04-17,Chin Up,Back,0.0,10.0,NaN
7,2017-04-17,Chin Up,Back,0.0,10.0,NaN
8,2017-04-17,Chin Up,Back,0.0,10.0,NaN
9,2017-04-17,Chin Up,Back,0.0,10.0,NaN
10,2017-04-17,Plank,Abs,0.0,30.0,NaN
11,2017-04-17,Plank,Abs,0.0,30.0,NaN
12,2017-04-17,Plank,Abs,0.0,30.0,NaN
13,2017-04-17,Plank,Abs,0.0,30.0,NaN
14,2017-04-17,Plank,Abs,0.0,30.0,NaN
15,2017-04-17,Glute-Ham Raise,Legs,10.0,12.0,NaN
16,2017-04-17,Glute-Ham Raise,Legs,10.0,12.0,NaN
17,2017-04-17,Glute-Ham Raise,Legs,10.0,12.0,NaN
18,2017-04-17,Glute-Ham Raise,Legs,10.0,12.0,NaN
19,2017-04-17,T-Bar Row,Back,45.0,12.0,NaN
20,2017-04-17,T-Bar Row,Back,45.0,12.0,NaN
21,2017-04-17,T-Bar Row,Back,45.0,12.0,NaN
22,2017-04-17,T-Bar Row,Back,45.0,12.0,NaN
23,2017-04-17,Seated Cable Row,Back,70.0,12.0,NaN
24,2017-04-17,Seated Cable Row,Back,70.0,12.0,NaN
25,2017-04-17,Seated Cable Row,Back,70.0,12.0,NaN
26,2017-04-17,Seated Cable Row,Back,70.0,12.0,NaN
27,2017-04-17,Rowing Machine,Cardio,NaN,NaN,NaN
28,2017-04-20,Safety Squat Bar,Legs,110.0,10.0,NaN
29,2017-04-20,Safety Squat Bar,Legs,110.0,8.0,NaN
...,...,...,...,...,...,...
1369,2018-01-06,Dumbbell Shoulder Press,Shoulders,22.5,12.0,NaN
1370,2018-01-06,Dumbbell Shoulder Press,Shoulders,22.5,12.0,NaN
1371,2018-01-06,Dumbbell Shoulder Press,Shoulders,22.5,8.0,NaN
1372,2018-01-06,V-Bar Push Down,Triceps,15.0,8.0,NaN
1373,2018-01-06,V-Bar Push Down,Triceps,15.0,8.0,NaN
1374,2018-01-06,V-Bar Push Down,Triceps,15.0,7.0,NaN
1375,2018-01-06,Single Arm Cable,Triceps,2.0,15.0,NaN
1376,2018-01-06,Single Arm Cable,Triceps,3.0,12.0,NaN
1377,2018-01-06,Single Arm Cable,Triceps,4.0,8.0,NaN
1378,2018-01-06,Incline Hammer Strength Chest Press,Chest,70.0,9.0,NaN
1379,2018-01-06,Incline Hammer Strength Chest Press,Chest,70.0,7.0,NaN
1380,2018-01-06,Incline Hammer Strength Chest Press,Chest,70.0,6.0,NaN
1381,2018-01-06,Incline Hammer Strength Chest Press,Chest,50.0,4.0,NaN
1382,2018-01-06,Lateral Dumbbell Raise,Shoulders,10.0,12.0,NaN
1383,2018-01-06,Lateral Dumbbell Raise,Shoulders,10.0,12.0,NaN
1384,2018-01-06,Lateral Dumbbell Raise,Shoulders,10.0,10.0,NaN
1385,2018-01-08,Belt Squat,Legs,80.0,20.0,NaN
1386,2018-01-08,Belt Squat,Legs,120.0,20.0,NaN
1387,2018-01-08,Barbell Squat,Legs,60.0,10.0,NaN
1388,2018-01-08,Barbell Squat,Legs,100.0,10.0,NaN
1389,2018-01-08,Barbell Squat,Legs,125.0,10.0,NaN
1390,2018-01-08,Barbell Squat,Legs,125.0,10.0,NaN
1391,2018-01-08,Barbell Squat,Legs,130.0,10.0,NaN
1392,2018-01-08,Unilateral Leg Press,Legs,80.0,15.0,NaN
1393,2018-01-08,Unilateral Leg Press,Legs,80.0,15.0,NaN
1394,2018-01-08,Unilateral Leg Press,Legs,80.0,15.0,NaN
1395,2018-01-08,Unilateral Leg Press,Legs,80.0,15.0,NaN
1396,2018-01-08,Glute-Ham Raise,Legs,0.0,10.0,NaN
1397,2018-01-08,Glute-Ham Raise,Legs,0.0,10.0,NaN
1398,2018-01-08,Glute-Ham Raise,Legs,0.0,9.0,NaN

In [11]:
data = data.drop(['Distance Unit','Distance','Time'], axis = 1)

In [12]:
data.head()

         Date  Exercise Category  Weight (kgs)  Reps Comment
0  2017-04-17  Deadlift     Back         150.0   3.0     NaN
1  2017-04-17  Deadlift     Back         155.0   3.0     NaN
2  2017-04-17  Deadlift     Back         160.0   3.0     NaN
3  2017-04-17  Deadlift     Back         165.0   3.0     NaN
4  2017-04-17  Deadlift     Back         170.0   3.0     NaN

In [20]:
Deadlift = data.loc[data['Exercise'] == 'Deadlift']
BackSquat = data.loc[data['Exercise'] == 'Barbell Squat']

In [15]:
Deadlift.head()

         Date  Exercise Category  Weight (kgs)  Reps Comment
0  2017-04-17  Deadlift     Back         150.0   3.0     NaN
1  2017-04-17  Deadlift     Back         155.0   3.0     NaN
2  2017-04-17  Deadlift     Back         160.0   3.0     NaN
3  2017-04-17  Deadlift     Back         165.0   3.0     NaN
4  2017-04-17  Deadlift     Back         170.0   3.0     NaN

In [19]:
Deadlift.describe()

       Weight (kgs)       Reps
count     51.000000  51.000000
mean     142.843137   4.411765
std       39.856052   3.256848
min       60.000000   1.000000
25%      125.000000   2.000000
50%      155.000000   3.000000
75%      172.500000   6.000000
max      200.000000  12.000000

In [21]:
BackSquat.head()

Empty DataFrame
Columns: [Date, Exercise, Category, Weight (kgs), Reps, Comment]
Index: []